// Generated by @dunx/create-app for dunxon-panel. Yours to edit.
import { Auth } from '@dunx/auth';
import { ConfigModule, Module } from '@dunx/core';
import { LoggerModule } from '@dunx/infra/logger';
import { AppConfigService, validate } from './config.js';
import { DocsModule } from './docs/docs.module.js';
import { HttpModule } from './http/http.module.js';
import { GuardsModule } from './guards/guards.module.js';
import { DatabaseModule } from './database/database.module.js';
import { UsersModule } from './users/users.module.js';
import { AccountsModule } from './auth/auth.module.js';
import { CacheModule } from './cache/cache.module.js';
import { ChatModule } from './chat/chat.module.js';
import { PicturesModule } from './pictures/pictures.module.js';
import { JobsModule } from './jobs/jobs.module.js';
import { StorageModule } from './storage/storage.module.js';
import { ProbesModule } from './health/health.module.js';
import { MaintenanceModule } from './schedule/schedule.module.js';
import { AssetsModule } from './assets/assets.module.js';
import { UpstreamModule } from './upstream/upstream.module.js';

/**
 * Import order is construction order, and shutdown runs in reverse - so config and
 * the logger are built first and torn down last, and anything a feature depends on
 * outlives it.
 */
@Module({
  imports: [
    ConfigModule.forRoot({ validate, as: AppConfigService }),
    // The level comes from the validated config, which is the one thing a
    // zero-argument `forRoot` function cannot reach.
    LoggerModule.forRootAsync(
      {
        useFactory: (config: AppConfigService) => ({
          name: config.get('appName'),
          level: config.get('log').level,
        }),
        inject: [AppConfigService] as const,
      },
      { captureGlobalErrors: true },
    ),
    DocsModule,
    HttpModule,
    GuardsModule,
    DatabaseModule,
    UsersModule,
    AccountsModule,
    CacheModule,
    ChatModule,
    PicturesModule,
    JobsModule,
    StorageModule,
    ProbesModule,
    MaintenanceModule,
    AssetsModule,
    UpstreamModule,
  ],
  // Better Auth serves its own routes, so the document is the only place they
  // appear - and `betterAuthDocument` needs the instance.
  exports: [Auth],
})
export class AppModule {}
