// Generated by @dunx/create-app for dunxon-panel. Yours to edit.
import { ConfigService, type ConfigSource, LogLevel } from '@dunx/core';
import { z } from 'zod';

/**
 * One validation function, which is the whole `ConfigModule` contract. dunx does
 * not pick the library - this is zod because the routes already use it, and a
 * hand-written function that throws would work identically.
 *
 * `.default()` is where a value comes from when the variable is unset, so a clean
 * checkout boots with no `.env` at all. Bun loads `.env` and `.env.local` itself,
 * so there is nothing here that reads a file.
 */
const envSchema = z.object({
  PORT: z.coerce.number().int().min(0).max(65535).default(3000),
  LOG_LEVEL: z.enum(LogLevel).default(LogLevel.INFO),
  /** Unset means console only. Set it to also append JSON to a rotating file. */
  LOG_FILE: z.string().optional(),
  /** Both cost a `req.clone().text()` on the hot path, so off in production. */
  LOG_REQUEST_BODY: z.stringbool().default(false),
  LOG_RESPONSE_BODY: z.stringbool().default(false),
  CORS_ORIGIN: z.string().default('https://example.com'),
  /**
   * Whether `x-forwarded-for` is believed. Off unless a trusted proxy is in
   * front: with nothing stripping the header, any caller picks its own
   * address, which fakes both rate limiting and the logged client address.
   */
  TRUST_PROXY: z.stringbool().default(false),
  /** `:memory:` needs no server and leaves nothing behind, so restarts are clean. */
  DATABASE_FILE: z.string().default(':memory:'),
  /** Absent is fine: the cache routes report themselves degraded instead of failing. */
  REDIS_URL: z.string().optional(),
  IMAGE_QUALITY: z.coerce.number().int().min(1).max(100).default(82),
  /** better-auth signs session cookies with this. 32 characters is its own minimum. */
  AUTH_SECRET: z
    .string()
    .min(32)
    .default('dunx-development-secret-not-for-production'),
  /** A `@Cron` that names no zone of its own runs in this one. */
  SCHEDULE_TZ: z.string().default('UTC'),
  /** Per-call budget for the outbound client. */
  UPSTREAM_TIMEOUT_MS: z.coerce.number().int().min(1).default(5000),
});

export interface AppConfig {
  readonly port: number;
  readonly appName: string;
  readonly log: {
    readonly level: LogLevel;
    readonly file: string | undefined;
    readonly requestBody: boolean;
    readonly responseBody: boolean;
  };
  readonly corsOrigin: string;
  readonly trustProxy: boolean;
  readonly database: { readonly file: string };
  readonly redis: { readonly url: string | undefined };
  readonly images: { readonly quality: number };
  readonly auth: { readonly secret: string };
  readonly seedUsers: readonly string[];
  readonly authorization: { readonly enabled: boolean };
  readonly schedule: { readonly tz: string };
  readonly upstream: { readonly timeoutMs: number };
}

/**
 * One name for the typed config everywhere. A subclass rather than
 * `ConfigService<AppConfig>` at each site because a factory's `inject: [...]`
 * carries no type argument - the class does, and it is a real runtime value, so it
 * is both a precise token and a usable constructor annotation.
 */
export class AppConfigService extends ConfigService<AppConfig> {}

/** The one broker channel the websocket relay carries every topic on. */
export const RELAY_CHANNEL = 'dunxon-panel:ws';

/** Flat variables in, a shaped object out. Nothing downstream reads `Bun.env`. */
export const validate = (env: ConfigSource): AppConfig => {
  const parsed = envSchema.safeParse(env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n - ');
    throw new Error(`Configuration is invalid:\n - ${issues}`);
  }
  const value = parsed.data;

  return {
    port: value.PORT,
    appName: 'dunxon-panel',
    log: {
      level: value.LOG_LEVEL,
      file: value.LOG_FILE,
      requestBody: value.LOG_REQUEST_BODY,
      responseBody: value.LOG_RESPONSE_BODY,
    },
    corsOrigin: value.CORS_ORIGIN,
    trustProxy: value.TRUST_PROXY,
    database: { file: value.DATABASE_FILE },
    redis: { url: value.REDIS_URL },
    images: { quality: value.IMAGE_QUALITY },
    auth: { secret: value.AUTH_SECRET },
    seedUsers: ['ada', 'grace'],
    authorization: { enabled: true },
    schedule: { tz: value.SCHEDULE_TZ },
    upstream: { timeoutMs: value.UPSTREAM_TIMEOUT_MS },
  };
};
