// Generated by @dunx/create-app for dunxon-panel. Yours to edit.
import { Auth, betterAuthDocument } from '@dunx/auth';
import { Logger } from '@dunx/core';
import { HttpFactory, RedisRelay, StaticFiles, type HttpApp } from '@dunx/http';
import { OpenApiModule } from '@dunx/openapi';
import { AppModule } from './app.module.js';
import { AppConfigService, RELAY_CHANNEL } from './config.js';
import { RequestTrailMiddleware } from './http/request-trail.js';

/**
 * One app for `bun run start`, `bun run dev` and the tests, and one file:
 * `createApp` is exported for a caller that wants the shape without a server, and
 * the block at the bottom serves it when this file is the entry point.
 *
 * `create()` boots the container and discovers routes and gateways; `listen()` is
 * what builds the `Bun.serve` route table. Everything between the two still gets to
 * shape it, and after `listen()` every one of those throws.
 */
export const createApp = async (): Promise<HttpApp> => {
  const app = await HttpFactory.create(
    OpenApiModule.forRootAsync({
      root: AppModule,
      inject: [Auth] as const,
      useFactory: (auth: Auth) => ({
        title: 'dunxon-panel',
        version: '0.1.0',
        contribute: [
          betterAuthDocument(auth, { basePath: '/api/auth', tag: 'Auth' }),
        ],
      }),
    }),
    {
      // Multi-node websocket fan-out on `Bun.RedisClient`, so it costs no
      // dependency. With no Redis running this degrades to single-process
      // behaviour, logs one warning, and the app still boots.
      websocket: { idleTimeout: 30 },
      relay: new RedisRelay({ connectionTimeout: 500 }),
      relayChannel: RELAY_CHANNEL,
    },
  );

  app.setGlobalPrefix('api');
  app.use(StaticFiles);
  app.use(RequestTrailMiddleware);
  app.set('trust proxy', true);
  app.enableCors({
    origin: app.get(AppConfigService).get('corsOrigin'),
    credentials: true,
    maxAge: 600,
  });

  return app;
};

const start = async (): Promise<void> => {
  const app = await createApp();
  app.enableShutdownHooks();

  const config = app.get(AppConfigService);
  const logger = app.get(Logger);
  const url = await app.listen(config.get('port'));

  logger.info(`listening on ${url}`);
  logger.info(`docs    ${new URL('api/docs', url).href}`);
  logger.info(`openapi ${new URL('api/openapi.json', url).href}`);
  logger.info(`health  ${new URL('api/health', url).href}`);

  // Nothing else to do: the server holds the process open, and the shutdown hooks
  // resolve this once a signal arrives.
  await app.closed;
};

// False when a test imports this file for `createApp` alone, which is what lets one
// module be both the entry point and the app's definition.
if (import.meta.main) {
  start().catch((error: unknown) => {
    console.error('failed to start', error);
    process.exit(1);
  });
}
